language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
env:
  - carbonVersion="^1.21"
install: 
  - php vendor/autoload.php
  - composer require nesbot/carbon:${carbonVersion}